version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:14
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwd
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_METRICS_ENABLED: true
      KC_DB_URL: postgres
      DB_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
    command:
      - start-dev
